# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'VS2017-Win2016' # 'Ubuntu-16.04', 'macOS-10.13'

variables:
  solution: '$(solution.filePath)'

steps:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=vsts
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: $(solution.filePath)
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    projects: $(project.webApiTestProject)
    command: 'test'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    projects: $(solution.filePath)
    command: 'publish'

- task: CmdLine@2
  inputs:
    script: 'dir $(Agent.BuildDirectory) /s /b'
    #workingDirectory: # Optional
    #failOnStderr: false # Optional

# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=vsts
- task: CopyFiles@2
  displayName: 'copy web api to staging directory'
  inputs:
    sourceFolder: 'BesiGourmet/BesiGourmet/bin/$(BuildConfiguration)/netcoreapp2.1'
    contents: 'publish.zip' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    #cleanTargetFolder: false # Optional
    #overWrite: false # Optional
    #flattenFolders: false # Optional

- task: CopyFiles@2
  displayName: 'copy arm template to staging directory'
  inputs:
    sourceFolder: 'BesiGourmet/ARM'
    contents: 'template.json' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    #cleanTargetFolder: false # Optional
    #overWrite: false # Optional
    #flattenFolders: false # Optional

# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=vsts
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'WebApi' 
    #publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional

#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'
